name: '🚀 - Feature Request'
title: '🚀 - '
description: Suggest a feature for the app
labels: ['feature']

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Proposed solution.
        Alternatives considered.
    validations:
      required: true
